/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns;

import java.util.*;
import java.io.*;
import java.util.stream.*;

public class Design {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Design().getGreeting());
    }
}
