/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package design.patterns;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
import java.io.*;
import java.util.stream.*;

class DesignTest {
    @Test void designHasAGreeting() {
        Design classUnderTest = new Design();
        assertNotNull(classUnderTest.getGreeting(), "Design should have a greeting");
    }
}
